language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-express-web-site' ]; then cd .. && eval "mv $currentfolder generator-express-web-site" && cd generator-express-web-site; fi
